### PR TITLE
Update 2024.md

### PR DESCRIPTION
**Pull request by imaabasiee**
Interface Themes: Played around with the themes. I noticed that when you click a particular theme and click on cancel, it does not revert to the previous theme.
Here is a video for the test outcome https://www.loom.com/share/d0b695fe6a3843cab7abe6e08ad6d3d8?sid=d5595364-7c42-40b8-90e8-d047caa4f627

### CODE REVIEW

**Review by imaabasiee — COMMENTED** [review]
Interface Theme: I played around with the themes and noticed that when you select a theme and cancels it, it does not revert to the previous one. Here is a video: https://www.loom.com/share/d0b695fe6a3843cab7abe6e08ad6d3d8?sid=6ce6f2c7-d1ed-4b4a-94e6-ccef15edf17e

**Comment by RCheesley** [comment]
Thanks for this! If you can include the link to the pr you tested in the description it would help us a lot to verify. The loom video needs posting on that pr when you approve. Just going to check out the pr.

**Comment by RCheesley** [comment]
@imaabasiee you still need to leave the actual review on the PR here: https://github.com/mautic/mautic/pull/13767 - go to files changed at the top as documented here: https://contribute.mautic.org/contributing-to-mautic/tester#leaving-your-review - click the Approve radio option and leave your Loom recording/description there. Thanks! Then we can count it as a contribution.

**Comment by MojisolaaaO** [comment]
@imaabasiee there is an existing bug ticket for this [#14171](https://github.com/mautic/mautic/issues/14171), so you can add that you were also able to reproduce it

**Comment by RCheesley** [comment]
Thanks for adding the review on the PR @imaabasiee ! I've resolved the conflict so this is good to go!

**Review by RCheesley — APPROVED** [review]

**Pull request merged**
