### PR TITLE
fix: holopin minimal setup

### PR DESCRIPTION
**Pull request by favour-chibueze**

### CODE REVIEW

**Review by fakela — APPROVED** [review]

**Comment by favour-chibueze** [comment]
@holopin-bot @fakela

**Comment by favour-chibueze** [comment]
@RCheesley I have tried different configuration and it's still not working.

**Comment by favour-chibueze** [comment]
@holopin-bot @favour-chibueze

**Comment by RCheesley** [comment]
Looking at the docs it seems like we might be missing some sections, but I am totally lost as to what is mandatory and what is not, whether the sticker bit is needed when awarding holobytes, etc. It's very vague.

This bit seems to be missing from our yaml file but it seems like it was maybe there before?

```
defaultSticker: cl7td8iq6014809k0mf12i1e6
stickers:
  - id: cl7td8iq6014809k0mf12i1e6
    alias: deserves-badge
```

Let's ask for help from Holopin instead of going round the houses fumbling around in the dark!

**Pull request merged**
